encoder-embed-dim-subtransformer: 384

encoder-layer-num-subtransformer: 13

encoder-ffn-embed-dim-all-subtransformer: [1152, 1344, 1152, 1344, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1344, 1536]

encoder-self-attention-heads-all-subtransformer: [6, 6, 5, 7, 5, 5, 5, 6, 6, 7, 7, 6, 7]